### ISSUE TITLE
Line 292-296 Change Text

### ISSUE THREAD

**Issue by mayaogasawara** [bidish-acharya/dwj-website#2]
@bidish-acharya 
1. Please check the edit below for line 292-296(I tried to edit the text in the coding), if it is ok please push changes. I just tried, so if it does not work let me know. 
 <div class="container-fluid">
    <div class="row significance reverseOnMobile">
    <div class="col-md-5 textSingle">
    <h2 class="blue-color revealOnScroll" data-animation='fadeInUp'><strong>開発メソッド</strong></h2>
    <ul class="p-3 list">
    	<i class="fas fa-check"></i><li class="revealOnScroll" data-animation='fadeInRight'>&nbsp; <strong>ラボ型</strong><br/>人月単位でご契約いただき、御社の専属チームを構成します。<br/>アジャイル形式に適した開発方法です。</li>
        <br />
       <i class="fas fa-check"></i><li class="revealOnScroll" data-animation='fadeInRight'>&nbsp; <strong>プロジェクト型</strong><br/>いわゆる受託開発です。<br/>事前に仕様書等が決まっている案件に適しています。</li>

**Comment by mayaogasawara** [comment]
@bidish-acharya 
Oops- I think that is how it is going to look like. Here's coding

 `<div class="container-fluid">
    <div class="row significance reverseOnMobile">
    <div class="col-md-5 textSingle">
    <h2 class="blue-color revealOnScroll" data-animation='fadeInUp'><strong>開発メソッド</strong></h2>
    <ul class="p-3 list">
    	<i class="fas fa-check"></i><li class="revealOnScroll" data-animation='fadeInRight'>&nbsp; <strong>ラボ型</strong><br/>人月単位でご契約いただき、御社の専属チームを構成します。<br/>アジャイル形式に適した開発方法です。</li>
        <br />
       <i class="fas fa-check"></i><li class="revealOnScroll" data-animation='fadeInRight'>&nbsp; <strong>プロジェクト型</strong><br/>いわゆる受託開発です。<br/>事前に仕様書等が決まっている案件に適しています。</li>`

**Comment by bidish-acharya** [comment]
@mayaogasawara 

Thank you for the coding. :) I have replaced it.
